srproject_django/accounts/urls.py
# The URLs provided by auth are:

# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url('signup', views.signup_view, name='signup'),
    url('login', views.login_view, name='login'),
    url('forgot-password', views.forgot_password_view, name='forgot-password'),
    url('logout', views.logout_view, name='logout'),
    # url('homepage_return', views.homepage_return, name='homepage_return'),
]

srproject_django/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),

]

srproject_django/srproject_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    # homepage urls
    path('', include('homepage.urls')),
    # admin urls
    path('admin/', admin.site.urls),
    # iotflash urls
    path('iotflash/', include('iotflash.urls')),
    # accounts urls
    path('accounts/', include('accounts.urls'))  # , include('django.contrib.auth.urls')),

]

urlpatterns += staticfiles_urlpatterns()

srproject_django/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

srproject_django/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            # log user in
            login(request, user)
            return redirect('devices:dashboard')
            # return redirect('iotflash/dashboard.html')

    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('devices:dashboard')

    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:login')


def forgot_password_view(request):
    return render(request, 'accounts/forgot-password.html')


def homepage_return(request):
    return render(request, 'homepage.html')

srproject_django/accounts/templates/accounts/accounts_template.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->

                    {% block content %}
                    {% endblock %}


                </div>
            </div>

        </div>

    </div>

    <div>
        <center><a href="{% url 'homepage:homepage' %}" class="btn btn-primary btn-user btn-sm">Back to home</a></center>
    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

srproject_django/accounts/templates/accounts/forgot-password.html
{% extends 'accounts/accounts_template.html' %}

{% block content %}

<!-- Nested Row within Card Body -->
<div class="row">
    <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
    <div class="col-lg-6">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link
                    to reset your password!</p>
            </div>
            <form class="user">
                <div class="form-group">
                    <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                           aria-describedby="emailHelp" placeholder="Enter Email Address...">
                </div>
                <a href="login" class="btn btn-primary btn-user btn-block">
                    Reset Password
                </a>
            </form>
            <hr>
            <div class="text-center">
                <a class="small" href="signup">Create an Account!</a>
            </div>
            <div class="text-center">
                <a class="small" href="login">Already have an account? Login!</a>
            </div>
        </div>
    </div>
</div>
</div>
</div>

</div>

</div>

</div>

{% endblock %}

srproject_django/accounts/templates/accounts/login.html
{% extends 'accounts/accounts_template.html' %}

{% block content %}

<div class="row">
    <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
    <div class="col-lg-6">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
            </div>



             <form class="custom-control" action="{% url 'accounts:login' %}" method="post">

                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                 {% endif %}
                 <br>
               <center><input class="btn btn-primary" type="submit" value="Login"></center>
            </form>

            <!--<form method="post">-->
                <!--<div class="form-group">-->


                    <!--&lt;!&ndash;{% csrf_token %}&ndash;&gt;-->
                    <!--&lt;!&ndash;{{ form.as_p }}&ndash;&gt;-->


                <!--</div>-->
                <!--<div class="form-group">-->
                <!--</div>-->
                <!--<div class="form-group">-->
                    <!--<div class="custom-control custom-checkbox small">-->
                        <!--<input type="checkbox" class="custom-control-input" id="customCheck">-->
                        <!--<label class="custom-control-label" for="customCheck">Remember Me</label>-->
                    <!--</div>-->
                <!--</div>-->
                <!--<a href="#" class="btn btn-primary btn-user btn-block">-->
                    <!--<button type="submit">Login</button>-->
                <!--</a>-->

            <!--</form>-->

            <hr>
            <div class="text-center">
                <a class="small" href="forgot-password">Forgot Password?</a>
            </div>
            <div class="text-center">
                <a class="small" href="signup">Create an Account!</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

srproject_django/accounts/templates/accounts/register.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                        </div>
                        <form class="user">
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="text" class="form-control form-control-user" id="exampleFirstName"
                                           placeholder="First Name">
                                </div>
                                <div class="col-sm-6">
                                    <input type="text" class="form-control form-control-user" id="exampleLastName"
                                           placeholder="Last Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                       placeholder="Email Address">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="password" class="form-control form-control-user"
                                           id="exampleInputPassword" placeholder="Password">
                                </div>
                                <div class="col-sm-6">
                                    <input type="password" class="form-control form-control-user"
                                           id="exampleRepeatPassword" placeholder="Repeat Password">
                                </div>
                            </div>
                            <a href="login" class="btn btn-primary btn-user btn-block">
                                Register Account
                            </a>
                            <hr>
                            <a href="" class="btn btn-google btn-user btn-block">
                                <i class="fab fa-google fa-fw"></i> Register with Google
                            </a>
                            <a href="" class="btn btn-facebook btn-user btn-block">
                                <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                            </a>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="forgot-password">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="login">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

srproject_django/accounts/templates/accounts/signup.html
{% extends 'accounts/accounts_template.html' %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an account</h1>
            </div>

            <form class="custom-control" action="/accounts/signup" method="post">

                {% csrf_token %}
                {{ form }}

                <input class="btn btn-primary" type="submit" value="Register">

            </form>


            <!--Sign up form-->
            <!--<form method="post">-->
            <!--<div class="form-group">-->
            <!--{% csrf_token %}-->
            <!--{{ form.as_p }}-->
            <!--</div>-->
            <!--<div class="form-group">-->
            <!--</div>-->
            <!--<div class="form-group">-->
            <!--<div class="custom-control custom-checkbox small">-->
            <!--<input type="checkbox" class="custom-control-input" id="customCheck">-->
            <!--<label class="custom-control-label" for="customCheck">Remember Me</label>-->
            <!--</div>-->
            <!--</div>-->
            <!--<a href="#" class="btn btn-primary btn-user btn-block">-->
            <!--<button type="submit">Login</button>-->
            <!--</a>-->
            <!--</form>-->

        </div>
    </div>
</div>


{% endblock %}