srproject_django/accounts/urls.py
# The URLs provided by auth are:

# accounts/login/ [name='login']
# accounts/logout/ [name='logout']
# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url('signup', views.signup_view, name='signup'),
    url('login', views.login_view, name='login'),
    url('forgot-password', views.forgot_password_view, name='forgot-password'),
    url('logout', views.logout_view, name='logout'),
    # url('homepage_return', views.homepage_return, name='homepage_return'),
]

srproject_django/iotflash/urls.py
# from django.urls import path
# from django.urls import path, include
# from django.views.generic.base import TemplateView
# from . import views

from django.conf.urls import url
from . import views

app_name = 'devices'

urlpatterns = [

    url('dashboard/', views.iotflash_dashboard, name='dashboard'),
    url('test-page/', views.iotflash_testpage, name='testpage'),
    url('applications/', views.app_view, name='applications'),
    url('device-table/', views.device_table_view, name='device-table'),
    url('device-chart/', views.device_chart_view, name='device-chart'),
    # url('^(?P<devID>[\w-]+)/$', views.iotflash_device_detail, name='details'),
    url('device-info', views.iotflash_device_detail, name='details'),
    url('profile-settings', views.iotflash_profile_settings, name='profile-settings'),

    # path('', views.base, name='base'),
    # path('dash', views.dash, name='dash'),
    # path('homepage', views.homepage),
    # path('blank', views.TESTINGPAGE),
    # path('login/homepageRedirect', views.homepageRedirect),

    # path('base', views.base),
    # path('', views.index, name='index'),
    # path('login', views.loginPage, name='login'),
    # path('register', views.registerPage, name='register'),
    # path('error404', views.error404Page, name='error404'),
    # path('forgot-password', views.forgotPassPage, name='forgot-password'),

    # path('buttons.html', views.buttons),
    # path('cards.html', views.cards),
    # path('charts.html', views.charts),
    # path('devices_table.html', views.tables),
    # path('ua', views.uaPage, name='ua'),
    # path('utilities-border.html', views.ub),
    # path('utilities-color.html', views.uc),
    # path('utilities-other.html', views.uo),

    # path('home', views.home)

]

srproject_django/srproject_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    # homepage urls
    path('', include('homepage.urls')),
    # admin urls
    path('admin/', admin.site.urls),
    # iotflash urls
    path('iotflash/', include('iotflash.urls')),
    # accounts urls
    path('accounts/', include('accounts.urls'))  # , include('django.contrib.auth.urls')),

]

urlpatterns += staticfiles_urlpatterns()

srproject_django/iotflash/models.py
from __future__ import unicode_literals
from djongo import models


# Each model is a class. Each class represents ONE table in a database
# Each type of data (Account, Users) is represented by it's own model
# Each model maps to a single table


class HumidityDevice(models.Model):  # Collection name
    # auto update when data is inserted
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    # auto update when data is altered
    updated_at = models.DateTimeField(auto_now_add=True, auto_now=False)

    # Documents
    device_id = models.CharField(max_length=20, null=True)
    device_name = models.CharField(max_length=20, null=True)
    device_location = models.CharField(max_length=100, null=True)
    sensor_type = models.CharField(max_length=20, null=True)
    subbed_topic = models.CharField(max_length=50, null=True)
    humidity_percentage = models.IntegerField(default=0, null=True)

    def __str__(self):
        return self.device_name

    class Meta:
        db_table = 'HumidityDevices'
        app_label = 'iotflash'
        # abstract = True


class TempDevice(models.Model):  # Collection name
    # auto update when data is inserted
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    # auto update when data is altered
    updated_at = models.DateTimeField(auto_now_add=True, auto_now=False)

    # Documents
    device_id = models.CharField(max_length=20, null=True)
    device_name = models.CharField(max_length=20, null=True)
    device_location = models.CharField(max_length=100, null=True)
    sensor_type = models.CharField(max_length=20, null=True)
    subbed_topic = models.CharField(max_length=50, null=True)
    temp_level = models.IntegerField(default=0, null=True)

    def __str__(self):
        return self.device_name

    class Meta:
        db_table = 'TempDevices'
        app_label = 'iotflash'
        # abstract = True

    objects = models.DjongoManager()

# ------------------------------------------------------------

#######################
#                     #
#  IotFlash Devices   #
#  Stored in MongoDB  #
#    Using Djongo     #
#                     #
#######################

# Humdity collection
# class HumidityDevices(models.Model):
#     collectionName = models.CharField(max_length=100)
#
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         # db_table = 'iotflash_db'
#         db_table = 'iotflashTest_db'
#         app_label = 'iotflash'


# Temperature collection
# class TempDevices(models.Model):
#     collectionName = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         # db_table = 'iotflash_db'
#         db_table = 'iotflashTest_db'
#         app_label = 'iotflash'


# ------------------------------------------------------------

# class Node(models.Model):
#     name = models.CharField(max_length=100)
#     creation_date = models.DateTimeField()
#     topic = models.CharField(max_length=100)
#     sensor = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         db_table = 'iotflash_db'
#         app_label = 'iotflash'
#
#
#
# class Data(models.Model):
#     node = models.ForeignKey(Node, on_delete=models.CASCADE)
#     creation_date = models.DateTimeField()
#     value = models.IntegerField(default=0, null=True)
#
#     # topic = models.CharField(default='', max_length=100)
#     # sensor = models.CharField(default='', max_length=100)
#
#     def __str__(self):
#         return self.node
#
#     class Meta:
#         db_table = 'iotflash_db'
#         app_label = 'iotflash'


# class User(models.Model):
#     user_id = models.IntegerField()
#     user_name = models.CharField(max_length=100)
#     user_pass = models.CharField(max_length=100)
#     email = models.CharField(max_length=100)
#
#     def __str__(self):
#         return self.user_name + " / " + self.user_id
#
#     class Meta:
#         db_table = 'users'
#         app_label = 'iotflash'
#     # class Meta:
#     #     db_table = 'auth'
#     #     app_label = 'auth_user'

srproject_django/iotflash/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import *


@login_required(login_url='/accounts/login)')
def iotflash_dashboard(request):
    humiditydevices = HumidityDevice.objects.all()
    tempdevices = TempDevice.objects.all()

    return render(request, 'iotflash/dashboard.html')
    # will be able to use when database working
    # return render(request, 'iotflash/dashboard.html', {'humdevs': humiditydevices, 'tempdevs': tempdevices})

def iotflash_profile_settings(request):

    return render(request, 'iotflash/profile_settings.html')


def iotflash_testpage(request):
    humiditydevices = HumidityDevice.objects.all()
    tempdevices = TempDevice.objects.all()

    return render(request, 'iotflash/blank.html', {'humdevs': humiditydevices, 'tempdevs': tempdevices})


def device_table_view(request):
    humiditydevices = HumidityDevice.objects.all()
    tempdevices = TempDevice.objects.all()
    return render(request, 'iotflash/devices_table.html', {'humdevs': humiditydevices, 'tempdevs': tempdevices})


def app_view(request):
    return render(request, 'iotflash/applications.html')


def device_chart_view(request):
    return render(request, 'iotflash/devices_chart.html')


# def iotflash_device_detail(request, devID):  # blank will be replaced with USER_ID from database
def iotflash_device_detail(request):  # blank will be replaced with USER_ID from database

    # humiditydevice = HumidityDevice.objects.get(devID=devID)
    # tempdevice = TempDevice.objects.get(devID=devID)
    # return render(request, 'iotflash/device_detail.html', {'humdevice': humiditydevice, 'tempdevice': tempdevice})
    return render(request, 'iotflash/device_info.html')


# def device_table_view(request):
#     return render(request, '/iotflash/devices_table.html')

# ---------------------------------------------------------------

# MOST RECENT USE THIS IS ANYTHING

# def error_404(request, exception):
#     return render(request, 'iotflash/404.html', {}, status=404)
#
# # class IndexView(generic.ListView):
# #     template_name = 'iotflash/details.html'
# #     context_object_name = 'nodes'
# #     def get_queryset(self):
# #         return Node.objects.order_by('id')
#
# def TESTINGPAGE(request):
#     return render_to_response('iotflash/blank.html') #blank will be replaced with USER_ID from database
#
# def homepage(request):
#     return render_to_response('iotflash/homepage.html')
#
# def homepageRedirect(request):
#     response = redirect('iotflash/homepage')
#     return response
#
# def base(request):
#     return render_to_response('iotflash/base.html')
#
# def loginHomeRedirect(request):
#     response = redirect('../..')
#     return response

# ------------------------------------------------------------------------------------

# def index(request):
#     # node_data = Node.objects.all()
#     # for field in node_data:
#     #     print('Device name: ', field.name)
#     #     print('Device ID: ', field.id)
#     #     print('Sensor type: ', field.sensor)
#     #     print('Topic: ', field.topic)
#     #
#     #     data_data = Data.objects.all()
#     # for field in data_data:
#     #         print('Device ID: ', field.id)
#     #         print('Device data value: ', field.value)
#
#     return render_to_response('iotflash/index.html')

# def dash(request):
#     return render_to_response('iotflash/index.html')

# def home(request):
#     return render_to_response('iotflash/home.html')

# def loginPage(request):
#     return render_to_response('iotflash/accounts_template.html')

# def registerPage(request):
#     return render_to_response('iotflash/register.html')
#
# def error404Page(request):
#     return render_to_response('iotflash/404.html')
#
# def forgotPassPage(request):
#     return render_to_response('iotflash/forgot-password.html')
#
# def uaPage(request):
#     return render_to_response('iotflash/utilities-animation.html')


# def index(request):
#     node_data = Node.objects.all()
#     for field in node_data:
#         print('Device name: ', field.name)
#         print('Device ID: ', field.id)
#         print('Sensor type: ', field.sensor)
#         print('Topic: ', field.topic)
#
#     data_data = Data.objects.all()
#     for field in data_data:
#         print('Device ID: ', field.id)
#         print('Device data value: ', field.value)
#
#     return HttpResponse("Items being printed in terminal")


# def buttons(request):
#     return render_to_response('iotflash/buttons.html')
#
# def cards(request):
#     return render_to_response('iotflash/cards.html')
#
# def charts(request):
#     return render_to_response('iotflash/charts.html')
#
# def tables(request):
#     return render_to_response('iotflash/devices_table.html')
#
# def ua(request):
#     return render_to_response('iotflash/utilities-animation.html')
#
# def ub(request):
#     return render_to_response('iotflash/utilities-border.html')
#
# def uc(request):
#     return render_to_response('iotflash/utilities-color.html')
#
# def uo(request):
#     return render_to_response('iotflash/utilities-other.html')

srproject_django/iotflash/templates/iotflash/applications.html
{% extends 'iotflash/base.html' %}

{% block content %}

<!-- Begin Page Content -->
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800">Applications</h1>
    <p class="mb-4">
        View various applications page. Add applications. Seperate from devices.
    </p>
    <div>
        <a href="#" class="btn btn-dark btn-icon-split">
                    <span class="icon text-gray-600">
                      <i class="fas fa-arrow-right"></i>
                    </span>
            <span class="text">Create New Application</span>
        </a>
    </div>

    <br>

    <div class="row">
        <div class="col-lg-4">
            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">

                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'devices:details' %}"> Sensors </a> </h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <center><h4 class="align-items-center">Number of Devices:</h4></center>
                    <center><h3 class="align-items-center">3</h3></center>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->

{% endblock %}

srproject_django/iotflash/templates/iotflash/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IoTFlash</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-laugh-wink"></i>
            </div>
            <div class="sidebar-brand-text mx-3">IoTFlash</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'devices:dashboard' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Navigation
        </div>

                <!-- Nav Item - Devices -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'devices:applications' %}">
                <i class="fab fa-elementor"></i>
                <span>Applications</span></a>
        </li>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'devices:device-chart' %}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>Charts</span></a>
        </li>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'devices:device-table' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Tables</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Search -->
                <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                               aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                             aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                           placeholder="Search for..." aria-label="Search"
                                           aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>


                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small"> Welcome, {{ user.first_name }}</span>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="{% url 'devices:profile-settings' %}">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Profile
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                Settings
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                Activity Log
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="accounts/login" data-toggle="modal"
                               data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                {% block content %}
                {% endblock %}


            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; IoTFlash 2019</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <!--<a class="btn btn-primary" href="{% url 'accounts:logout' %}">Logout</a>-->
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
  <script src="{% static 'js/demo/chart-bar-demo.js' %}"></script>

</body>

</html>

srproject_django/iotflash/templates/iotflash/dashboard.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--<meta charset="UTF-8">-->
<!--<title>Dashboard Placeholder</title>-->
<!--</head>-->
<!--<body>-->

{% extends 'iotflash/base.html' %}

{% block content %}
<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Dashboard</h1>


    <!-- Content Row -->
    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-12 mb-4">

            <!-- Project Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Senior Project</h6>
                </div>
                <div class="card-body">
                    <h4 class="small font-weight-bold">Database Setup<span class="float-right">50%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 50%" aria-valuenow="50"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">IotFlash Integration <span class="float-right">36%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-warning" role="progressbar" style="width: 36%" aria-valuenow="36"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Graduation <span class="float-right">98%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar" role="progressbar" style="width: 98%" aria-valuenow="98"
                             aria-valuemin="0"
                             aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Website Visualizations <span class="float-right">72%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-info" role="progressbar" style="width: 72%" aria-valuenow="72"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Senior Paper Rough Draft<span class="float-right">90%</span></h4>
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 90%" aria-valuenow="90"
                             aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>


    <div class="devices">
        {% for humiditydevice in humdevs %}

        <div class="col-lg-4">
            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">

                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary"><a
                            href="{% url 'devices:details' devID=HumidityDevices.device_name %} ">{{
                        HumidityDevices.device_name }}</a></h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Options:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    Overview:
                    <br>
                    Date created: {{ HumidityDevice.created_at }}
                    <br>
                    Name: {{ HumidityDevice.device_name }}
                    <br>
                    Sensor: {{ HumidityDevice.sensor_type }}
                    <br>
                    Topic: {{ HumidityDevice.subbed_topic }}
                    <br>
                    Recent Humidity Percent: {{ HumidityDevice.humidity_percentage }}
                </div>
            </div>
        </div>

        {% endfor %}


        {% for tempdevice in tempdevs %}

        <div class="col-lg-4">
            <!-- Dropdown Card Example -->
            <div class="card shadow mb-4">

                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{ TempDevice.device_name }}</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                             aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Options:</div>
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    Overview:
                    <br>
                    Date created: {{ TempDevice.created_at }}
                    <br>
                    Name: {{ TempDevice.device_name }}
                    <br>
                    Sensor: {{ TempDevice.sensor_type }}
                    <br>
                    Topic: {{ TempDevice.subbed_topic }}
                    <br>
                    Recent Temperature Level: {{ TempDevice.temp_level }}
                </div>
            </div>
        </div>

        {% endfor %}

    </div>

    {% endblock %}
</div>
<!--</body>-->
<!--</html>-->